### ISSUE TITLE
rpool devices=off?

### ISSUE THREAD

**Issue by nahall** [HankB/Linux_ZFS_Root#14]
I hit a strange issue running LXD in a snap on Debian and traced it back to nodev being set on the filesystem mount, which was caused because rpool/lxd inherited the "devices=off" property from rpool, which was set up using this script.

So I was going to just set devices=on for rpool/lxd, but upon further review, I'm wondering what is the rationale for devices=off for rpool which is done with the line in the script:

zfs set devices=off "${ROOT_POOL_NAME}"

I checked the [Debian Buster Root on ZFS Guide](https://openzfs.github.io/openzfs-docs/Getting%20Started/Debian/Debian%20Buster%20Root%20on%20ZFS.html) and I see where devices=off is set on the bpool, but not the rpool.

I'm just trying to figure out when would be good to default to devices=on and when would be good to default to devices=off as I've never dealt with this before.

**Comment by HankB** [comment]
Apologies for the delay in replying. Apparently at some point in upgrading the script to match the changing instructions I eliminated 

```text
zfs set devices=off "${ROOT_POOL_NAME}"\
```

I have no idea why it was there in the first place except to suppose I either got that from the instructions or misapplied the instructions.
