### ISSUE TITLE
Add DNS during the installation

### ISSUE THREAD

**Issue by humphreylee** [HankB/Linux_ZFS_Root#21]
I had issue that I can't connect to Internet after basic system installation (after the script and rebooted), despite having the correct driver for Wifi or Ethernet. I fix this after adding google DNS into my system.
`echo nameserver 8.8.8.8 > /etc/resolv.conf`

So, may be this is something that you should consider adding into the script.

**Comment by HankB** [comment]
This would be a DHCP server configuration issue (if you are using DHCP) or a manual configuration issue if you are manually configuring your network interfaces and beyond the scope of installing Debian root on ZFS.
